spring:
    application:
        name: api-payments
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: 
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            jdbc:
                lob.non-contextual-creation: true
    output:
        ansi:
            enabled: ALWAYS
server:
    port: 8081

logging:
    level:
        org:
            springframework:
                security: TRACE
